language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  - OCAML_VERSION=4.07 PACKAGE=act
os:
  - linux
